### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#35]
getting default Not Found Error currently. should be designed according to UI.

**Comment by HargovindArora** [comment]
@codehimanshu :+1:

**Comment by HargovindArora** [comment]
@codehimanshu will the new templates for 404 pages be in clients app or mainapp?

**Comment by MakChan** [comment]
@HargovindArora are you making the template?

**Comment by codehimanshu** [comment]
@HargovindArora make the URLs and point it to a particular template.
@MakChan you can design that template.

**Comment by codehimanshu** [comment]
@HargovindArora make the URLs and point to a template
@MakChan make the template

**Comment by MakChan** [comment]
@HargovindArora I've added the error template into the templates folder.

**Comment by HargovindArora** [comment]
@MakChan ok!
