### ISSUE TITLE
fix UI of project image thumbnail

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#39]
The project image is not responsive. It should be placed along side the content. Also if possible, restriction to height and width ration should be added.

**Comment by HargovindArora** [comment]
@codehimanshu I am adding the height and width restrictions according to user

**Comment by codehimanshu** [comment]
Okay, but the images seem to appear distorted. See the Crack the shell image on gdgjss.in
We need to fix this kind of issue, in case user uploads too wide or too long image.

**Comment by HargovindArora** [comment]
@codehimanshu By adding those fields for image and height we can set the standard for height and width of our images to be uploaded. Will this do the required?
