### ISSUE TITLE
fix footer content

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#41]
the gdg logo on right seems to be above the the left and middle footer. align them at same level.

![screenshot from 2017-10-01 00 02 48](https://user-images.githubusercontent.com/14791631/31048520-230b7306-a63c-11e7-9357-d4920444310f.png)

**Comment by malikshubham827** [comment]
I would like to take this one.

**Comment by malikshubham827** [comment]
@codehimanshu  Where do you want the logo for small screens <768px. On the next line in the center?

**Comment by codehimanshu** [comment]
@malikshubham827 on samll screens we can hide the logo. Its already there in the navbar I hope.
