### ISSUE TITLE
update content and images on homepage

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#42]
these should be changed
![screenshot from 2017-10-01 00 06 05](https://user-images.githubusercontent.com/14791631/31048526-5fac32c8-a63c-11e7-914b-bb337699a228.png)

**Comment by mani87** [comment]
Where i can find the new images? @codehimanshu

**Comment by codehimanshu** [comment]
@mani87 these will be added by our team. Still need to do some working on content and images.
