### ISSUE TITLE
decrease height of section

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#43]
on homepage this is occupying too much height
![screenshot from 2017-10-01 00 07 45](https://user-images.githubusercontent.com/14791631/31048538-a1177cae-a63c-11e7-896c-f18d03febbe9.png)

**Comment by pranay414** [comment]
Hey, I would like to take up this issue.

**Comment by codehimanshu** [comment]
sure, go ahead.

**Comment by pranay414** [comment]
Can you tell me how to go to this page?

**Comment by codehimanshu** [comment]
This is the homepage. After installation of project, head over to http://localhost:8000
this file is used as template: website/client/templates/client/index.html

**Comment by pranay414** [comment]
I am getting Google maps page with "JSS College" marked on it.

**Comment by codehimanshu** [comment]
check the access to static files in your developer console. might be we missed that in setup. If the css and js show 404, feel free to create an Issue.

**Comment by pranay414** [comment]
@codehimanshu yeah you missed the static files in setup.

**Comment by pranay414** [comment]
@codehimanshu this issue has been fixed.

**Comment by saurabhranjan1806** [comment]
the issue is fixed now
