### ISSUE TITLE
handle 0 events message

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#44]
In events section, there might not be any events in ongoing section, or in upcoming section, some motivative text should be added there if count is 0.

**Comment by saurabhranjan1806** [comment]
i would like to take this issue

**Comment by saurabhranjan1806** [comment]
@MakChan can u do this?

**Comment by MakChan** [comment]
I'll try.

**Comment by codehimanshu** [comment]
@MakChan any update?

**Comment by MakChan** [comment]
@codehimanshu Pretty much complete. I'll push it soon.

**Comment by MakChan** [comment]
It's done. Review it.
