### ISSUE TITLE
the active link in navbar

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#47]
Currently active link (the team on teams page, home on homepage) should have href=# instead of reloading the page

**Comment by mani87** [comment]
@codehimanshu href=(original url of the file) right?
And is it to apply on both the pages i.e. team.html and index.html?
Thankyou:)

**Comment by codehimanshu** [comment]
The url needs to be dynamic, if it's a team page, the na bar should contain # in link to team. Probably a variable named title should be passed from view to each template telling which page it is. And in Navarro template it should be checked correspondingly.

**Comment by mani87** [comment]
@codehimanshu can you please check my PR.
Thankyou:)
