### ISSUE TITLE
failed to load static files

### ISSUE THREAD

**Issue by pranay414** [GDG-JSS-NOIDA/website#52]
Right now in development mode when we try to reach http://127.0.0.1:8000, we are getting a google map instead of complete homepage. It is because we missed static files.

**Comment by malikshubham827** [comment]
Yes I am also facing the same issue. We may however just use the index.html file in the mean time.
![screen shot 2017-10-01 at 12 53 31 am](https://user-images.githubusercontent.com/13511528/31048801-185ae25a-a643-11e7-9137-8b3d93438e07.png)

**Comment by codehimanshu** [comment]
We are working on it. Will be fixed in some time. By the time you can go by visiting the html page directly.

**Comment by saurabhranjan1806** [comment]
it is now resolved.
