### ISSUE TITLE
Remove inline CSS

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#73]
In client app, there are many inline CSS, these should be moved to static files.

**Comment by anandpotukchi** [comment]
I would like to take this issue up @codehimanshu

**Comment by anandpotukchi** [comment]
Read doc. Now what? Any pep talk? Or do i get started?

**Comment by ralph9** [comment]
I'd like to be assigned to this issue, in case @anandpotukchi isn't yet.

**Comment by codehimanshu** [comment]
@anandpotukchi you can go ahead on removing the inline CSS, let us know if you are willing to take up this issue.
@ralph9 I think @anandpotukchi might be willing to take this up. Feel free to take up another issue.
