### ISSUE TITLE
remove unwanted code

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#74]
A lot of old junk code is present which is irrelevent. Also some of commented codes are no more required. these should be removed.

**Comment by Barathwaja** [comment]
ok @codehimanshu let me check this ... !!

**Comment by Barathwaja** [comment]
ok @codehimanshu let me check... !!

**Comment by Barathwaja** [comment]
@codehimanshu so much of unwanted jquery versions and bootstrap's .. :\

**Comment by Barathwaja** [comment]
@codehimanshu PR [https://github.com/GDG-JSS-NOIDA/website/pull/82](https://github.com/GDG-JSS-NOIDA/website/pull/82) .. an updated HTML. Plus the live site has more contents than this repo right??

**Comment by suleimanbashiru** [comment]
Is this issue still open.

**Comment by codehimanshu** [comment]
@Barathwaja Merged, thanks for your contribution.
