### ISSUE TITLE
add meta image

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#76]
No image comes up on adding the link to any social networking sites.
![screenshot from 2017-10-06 21 32 10](https://user-images.githubusercontent.com/14791631/31287199-1a6f761a-aade-11e7-848f-666b34546cbf.png)

**Comment by ApCoder123** [comment]
@codehimanshu I'll work on this issue.

**Comment by codehimanshu** [comment]
@ApCoder123 merged, thanks for your contribution.
